services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: example_db
      POSTGRES_DB: sac_db
    container_name: sac_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
