

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/navbar/Navbar";
import NavbarContainer from "@/components/navbar/NavbarContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className=" scroll-smooth font-[Cera-pro] bg-[url(/backgroundLanding.jpeg)] bg-no-repeat bg-cover bg-center backdrop-opacity-100 backdrop-blur-xs ">
      <body className={`${geistSans.variable} ${geistMono.variable} `}>
        <NavbarContainer/>
        {children}
      </body>
    </html>

  );
    
  }


