import type { Metadata } from "next";

import "./globals.css";
import NavbarContainer from "@/components/navbar/NavbarContainer";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "SAC-2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <NavbarContainer />
        {children}
        <Footer/>
      </body>
    </html>
  );

}


